language: node_js
node_js:
  - "10"

# 缓存yarn安装的包
cache:
  yarn: true

install:
  - yarn install 

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  name: guaguaerhao
  email: 2809731342@qq.com
  on:
    branch: master